services:
  runner:
    image: docker.io/gitea/act_runner:nightly-dind
    privileged: true
    restart: always
    volumes:
      - ./volumes/config.yaml:/config.yaml
      - ./volumes/data:/data
      - ./volumes/docker/data:/var/lib/docker
      - ./volumes/docker/sock:/var/run
    environment:
      CONFIG_FILE: /config.yaml
      GITEA_INSTANCE_URL: ${GITEA_INSTANCE_URL}
      GITEA_RUNNER_REGISTRATION_TOKEN: ${GITEA_RUNNER_REGISTRATION_TOKEN}
