name: easy_gitea_runner

services:
  gitea_runner:
    image: docker.io/gitea/act_runner:latest
    container_name: gitea_runner
    restart: always
    ports:
      - ${GITEA_RUNNER_CACHE_PORT:-32999}:${GITEA_RUNNER_CACHE_PORT:-32999}
    volumes:
      - ./volumes/config.yaml:/config.yaml
      - ./volumes/data:/data
      - ${DOCKER_SOCK_PATH:-/var/run/docker.sock}:/var/run/docker.sock
    environment:
      - CONFIG_FILE=/config.yaml
      - GITEA_INSTANCE_URL=${GITEA_INSTANCE_URL}
      - GITEA_RUNNER_REGISTRATION_TOKEN=${GITEA_RUNNER_REGISTRATION_TOKEN}
