services:
  runner:
    image: docker.io/gitea/act_runner:nightly-dind
    privileged: true
    restart: always
    volumes:
      - ./volumes/runner/config.yaml:/config.yaml
      - ./volumes/runner/data:/data
      - ./volumes/runner/actcache:/root/.cache/actcache
      - ./volumes/docker/run:/var/run
    environment:
      CONFIG_FILE: /config.yaml
      GITEA_INSTANCE_URL: ${GITEA_INSTANCE_URL}
      GITEA_RUNNER_REGISTRATION_TOKEN: ${GITEA_RUNNER_REGISTRATION_TOKEN}
