name: easy_gitea_runner

services:
  gitea_runner:
    image: docker.io/gitea/act_runner:nightly-dind
    container_name: gitea_runner
    privileged: true
    restart: always
    volumes:
      - ./volumes/config.yaml:/config.yaml
      - ./volumes/data:/data
    environment:
      CONFIG_FILE: /config.yaml
      GITEA_INSTANCE_URL: ${GITEA_INSTANCE_URL}
      GITEA_RUNNER_REGISTRATION_TOKEN: ${GITEA_RUNNER_REGISTRATION_TOKEN}
